# Generated by Django 5.1.1 on 2025-12-20 16:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('general', 'General Facilities'), ('food', 'Food & Drink'), ('wellness', 'Wellness & Spa'), ('business', 'Business Facilities'), ('transport', 'Transportation'), ('safety', 'Safety & Security')], default='general', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome or other icon class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='12:00')),
                ('cancellation_policy', models.TextField(help_text='Cancellation policy details')),
                ('payment_policy', models.TextField(help_text='Payment and deposit policy')),
                ('child_policy', models.TextField(blank=True, help_text='Policies regarding children')),
                ('pet_policy', models.TextField(blank=True, help_text='Policies regarding pets')),
                ('additional_info', models.TextField(blank=True, help_text='Any additional policies')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelFacilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_mappings', to='hotels.hotelfacility')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_mappings', to='hotels.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'facility')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('hotel', 'user')},
            },
        ),
    ]
