# Generated by Django 5.1.1 on 2025-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelfacility_hotelpolicy_roomimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-wifi', 'fa-swimming-pool')", max_length=50),
        ),
    ]
