# Generated by Django 5.1.1 on 2025-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_contact_email_hotel_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='Reservation status: pending, confirmed, or cancelled.', max_length=20),
        ),
    ]
