# Generated by Django 5.1.1 on 2025-12-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_userprofile'),
        ('hotels', '0006_remove_hotel_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='hotels.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
